// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj43k09Bmhu82hF_D4xFgEZHkL_oKtzV8',
    appId: '1:812972100101:android:b2841d5dc5533b7660ea6c',
    messagingSenderId: '812972100101',
    projectId: 'example-97544',
    storageBucket: 'example-97544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhz_D_4gaBp92aPvn03qBLBl1JVu3qhA',
    appId: '1:812972100101:ios:f7a88dc1da63ebdf60ea6c',
    messagingSenderId: '812972100101',
    projectId: 'example-97544',
    storageBucket: 'example-97544.firebasestorage.app',
    iosBundleId: 'com.example.moviesDb',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqEuThAbbtRW2t7VzEi51596bI7IzIVzk',
    appId: '1:812972100101:web:0cd9f9d6f1254a0360ea6c',
    messagingSenderId: '812972100101',
    projectId: 'example-97544',
    authDomain: 'example-97544.firebaseapp.com',
    storageBucket: 'example-97544.firebasestorage.app',
    measurementId: 'G-5SV6TE9885',
  );

}